name: MIS REPORT
on:
  push:
    branches:
      - main
      - Feture/Enhancement
  workflow_dispatch:
jobs:
  misreport:
    runs-on: ubuntu-latest
  services:
      MySQL:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD:
          MYSQL_DATABASE: mis_reports
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      steps:
      - name: Checkout code
        uses: actions/checkout@v3

