<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <style>
        body  { font-family: Arial, sans-serif; font-size: 13px; color: #222; background: #f7f9fb; margin: 0; padding: 0; }
        .wrap { max-width: 560px; margin: 30px auto; background: #fff; border-radius: 8px; box-shadow: 0 2px 8px rgba(0,0,0,.08); overflow: hidden; }
        .hdr  { background: #0c4a6e; color: #fff; padding: 24px 28px; }
        .hdr h1 { margin: 0; font-size: 18px; }
        .hdr p  { margin: 4px 0 0; font-size: 12px; opacity: .8; }
        .body { padding: 24px 28px; }
        .badge { display:inline-block; background:#0369a1; color:#fff; font-size:11px; font-weight:700; padding:2px 10px; border-radius:20px; margin-bottom:14px; letter-spacing:.5px; }
        .info-box { background:#f0f9ff; border:1px solid #bae6fd; border-radius:6px; padding:14px 16px; margin:14px 0; font-size:12px; color:#0c4a6e; }
        .info-box strong { display:block; font-size:13px; margin-bottom:4px; }
        .footer { background: #f0f4fa; padding: 14px 28px; font-size: 11px; color: #666; }
    </style>
</head>
<body>
<div class="wrap">
    <div class="hdr">
        <h1>BRM {{ $periodLabel }} Report</h1>
        <p>{{ ucfirst($branch) }} &nbsp;|&nbsp; {{ $fromFormatted }} — {{ $toFormatted }}</p>
    </div>
    <div class="body">
        <span class="badge">{{ strtoupper($period) }}</span>
        <p>Please find the <strong>Business Revenue Management (BRM) {{ $periodLabel }} Report</strong> for <strong>{{ ucfirst($branch) }}</strong> attached.</p>

        <div class="info-box">
            <strong>Report Period</strong>
            {{ $fromFormatted }} &nbsp;to&nbsp; {{ $toFormatted }}
        </div>

        <p style="font-size:12px; color:#444;">The Excel file contains three sheets:</p>
        <ul style="font-size:12px; color:#444; margin:0 0 14px; padding-left:18px; line-height:1.8;">
            <li><strong>ER IP</strong> — Doctor-wise ER &amp; IP revenue broken down by service category</li>
            <li><strong>OP SERVICES</strong> — Doctor-wise OP revenue by service category</li>
            <li><strong>OP CONSULTATIONS</strong> — Doctor-wise OP consultation count and revenue</li>
        </ul>

        <p style="color:#555; font-size:11px;">This is an automated {{ $period }} report. Contact the MIS team for queries.</p>
    </div>
    <div class="footer">
        Automated BRM report generated by the MIS system. Do not reply to this email.<br>
        Generated at {{ now()->format('d M Y, h:i A') }}
    </div>
</div>
</body>
</html>
