<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <style>
        body  { font-family: Arial, sans-serif; font-size: 13px; color: #222; background: #f7f9fb; margin: 0; padding: 0; }
        .wrap { max-width: 560px; margin: 30px auto; background: #fff; border-radius: 8px; box-shadow: 0 2px 8px rgba(0,0,0,.08); overflow: hidden; }
        .hdr  { background: #1e3a5f; color: #fff; padding: 24px 28px; }
        .hdr h1 { margin: 0; font-size: 18px; }
        .hdr p  { margin: 4px 0 0; font-size: 12px; opacity: .8; }
        .body { padding: 24px 28px; }
        table { width: 100%; border-collapse: collapse; margin: 16px 0; }
        th, td { padding: 7px 10px; border: 1px solid #e5e7eb; font-size: 12px; }
        th { background: #f0f4fa; font-weight: 700; text-align: left; }
        td { text-align: right; }
        td:first-child { text-align: left; }
        .footer { background: #f0f4fa; padding: 14px 28px; font-size: 11px; color: #666; }
    </style>
</head>
<body>
<div class="wrap">
    <div class="hdr">
        <h1>MIS Daily Report</h1>
        <p>{{ ucfirst($branch) }} &nbsp;|&nbsp; {{ $date }}</p>
    </div>
    <div class="body">
        <p>Please find the MIS report summary for <strong>{{ ucfirst($branch) }}</strong> dated <strong>{{ $date }}</strong> attached as a PDF.</p>

        @php
            $t = $reportData['totals'] ?? [];
            $v = $reportData['volume']['ftd'] ?? [];
        @endphp

        <table>
            <tr><th>Metric</th><th>FTD</th><th>MTD</th></tr>
            <tr><td>Total Sales</td>
                <td>₹{{ number_format(($reportData['totals']['sales_ftd'] ?? 0)/100000, 2) }}L</td>
                <td>₹{{ number_format(($reportData['totals']['sales_mtd'] ?? 0)/100000, 2) }}L</td>
            </tr>
            <tr><td>Collection</td>
                <td>₹{{ number_format(($reportData['totals']['collection_ftd'] ?? 0)/100000, 2) }}L</td>
                <td>₹{{ number_format(($reportData['totals']['collection_mtd'] ?? 0)/100000, 2) }}L</td>
            </tr>
            <tr><td>Occupancy</td>
                <td>{{ $v['occupancy'] ?? 0 }} ({{ $v['occupancy_pct'] ?? 0 }}%)</td>
                <td>—</td>
            </tr>
            <tr><td>Admissions</td>
                <td>{{ $v['admission'] ?? 0 }}</td>
                <td>{{ $reportData['volume']['mtd']['admission'] ?? 0 }}</td>
            </tr>
            <tr><td>Total OP</td>
                <td>{{ $v['total_op'] ?? 0 }}</td>
                <td>{{ $reportData['volume']['mtd']['total_op'] ?? 0 }}</td>
            </tr>
        </table>

        <p style="color:#555; font-size:11px;">The full report is attached as a PDF. If you have any queries, please contact the MIS team.</p>
    </div>
    <div class="footer">
        This is an automated report generated by the MIS system. Do not reply to this email.<br>
        Generated at {{ $reportData['generated_at'] ?? now() }}
    </div>
</div>
</body>
</html>
